import behaviorMap from '../../public/data/behavior-map.json';

/**
 * The behaviour contract per registry item, generated by
 * `scripts/build-behavior-map.mjs` from the tests and sources that ENFORCE it.
 *
 * Read the header of that script for where each field comes from. The rule
 * that matters here: nothing in this file is authored, so the `/c/<name>`
 * Behavior section cannot claim a keystroke that no test presses or a contrast
 * ratio the theme lock would reject.
 */

export type ThemeScheme = { theme: string; scheme: string };

export type KeyboardStep = {
  /** The `step()` title from the Storybook `play` function, verbatim. */
  title: string;
  /** Keys the step presses, in order. `Shift+F10`, `Tab`, `Space`, … */
  keys: string[];
};

export type KeyboardPath = {
  storyId: string;
  storyExport: string;
  storyFile: string;
  steps: KeyboardStep[];
  /** In `KEYBOARD_DRIVEN` + `MUST_ASSERT_ESCAPE` — Escape is locked, not just exercised. */
  escapeLocked: boolean;
};

export type ContrastRow = {
  fg: string;
  bg: string;
  kind: 'text' | 'non-text';
  /** WCAG 2.2 floor this pair is held to: 4.5 for text, 3 for non-text. */
  floor: number;
  why: string;
  /** One ratio per column of `MATRIX`, in the same order. */
  ratios: number[];
  worst: number;
  worstAt: ThemeScheme;
  passes: boolean;
};

export type TextAlternative = {
  kind:
    | 'series-table'
    | 'series-table-consumer'
    | 'sr-only-table'
    | 'sr-only-copy'
    | null;
  detail: string | null;
};

export type ComponentBehavior = {
  /**
   * Repo-relative path of the component's real source, probed against the
   * filesystem at build time. `null` for meta-items (the starters) that ship
   * no single file of their own.
   */
  sourcePath: string | null;
  keyboard: KeyboardPath | null;
  contrast: ContrastRow[];
  textAlternative: TextAlternative;
  /** The `DataStateName` union, when this component consumes the state model. */
  states: string[];
  coverage: { inGate: boolean };
};

export type DataStateFacet = {
  name: string;
  short: string | null;
  glyph: string | null;
  emphasis: string | null;
  hatch: boolean;
  dashed: boolean;
  /** `replaces` stands instead of the body; `qualifies` stands next to it. */
  role: 'replaces' | 'qualifies' | 'none';
};

export type BehaviorMap = {
  generatedAt: string;
  sources: {
    keyboard: string;
    keyboardLock: string;
    contrast: string;
    themes: string[];
    dataStates: string;
    coverage: string;
  };
  coverage: {
    file: string;
    thresholds: Record<string, number>;
    include: string[];
  };
  contrastFloors: Record<string, number>;
  matrix: ThemeScheme[];
  dataStates: DataStateFacet[];
  components: Record<string, ComponentBehavior>;
};

const MAP = behaviorMap as BehaviorMap;

export const behaviorFor = (name: string): ComponentBehavior | null =>
  MAP.components[name] ?? null;

/** The theme × scheme columns every `ContrastRow.ratios` array lines up with. */
export const MATRIX = MAP.matrix;
export const DATA_STATES = MAP.dataStates;
export const COVERAGE = MAP.coverage;
export const SOURCES = MAP.sources;

/**
 * True when this component has anything behavioural to say at all.
 *
 * A `registry:style` item or a pure type file has no keyboard path, no colour
 * pair and no text equivalent — and a "Behavior" heading over four empty cells
 * is worse than no heading, because it teaches the reader the section is
 * decorative.
 */
export const hasBehavior = (b: ComponentBehavior | null): boolean =>
  b !== null &&
  (b.keyboard !== null ||
    b.contrast.length > 0 ||
    b.textAlternative.kind !== null ||
    b.states.length > 0);
