import storyMap from '../../public/data/story-map.json';

/**
 * Storybook story ids per registry item, generated by
 * `scripts/build-story-map.mjs` from the story sources in this repo.
 * See `src/components/story-preview.tsx` for why the previews are embedded.
 */

export type StoryEntry = {
  title: string;
  storyIds: string[];
  /** Best "just show me the component" story. */
  preview: string | null;
  /** The `--dark` twin of `preview`, when the component has one. */
  previewDark: string | null;
  /** Dedicated Loading/Skeleton story, when one exists. */
  skeleton: string | null;
};

const MAP = storyMap as Record<string, StoryEntry>;

export const storiesFor = (name: string): StoryEntry | null => MAP[name] ?? null;

/**
 * Extra stories worth showing beyond the main preview — the `--dark` and
 * `--rtl` variants are mechanical duplicates of the default, so they're the
 * two that get dropped.
 */
export const exampleStories = (entry: StoryEntry): string[] =>
  entry.storyIds.filter(
    (id) =>
      id !== entry.preview &&
      !id.endsWith('--docs') &&
      !id.endsWith('--dark') &&
      !id.endsWith('--rtl'),
  );
