import type { Metadata } from 'next';
import Link from 'next/link';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { SiteNav } from '@/components/site-nav';

export const metadata: Metadata = {
  title: 'Semantics Catalogue',
  description:
    'Every Interlace semantic token — its value in light + dark, the brand primitive it resolves to, and its purpose. Auto-generated from packages/ui/styles/interlace-theme.css at build time.',
  openGraph: {
    title: 'Semantics Catalogue — Interlace DS',
    description:
      'Browse every semantic token (--background, --foreground, --muted-foreground, …) and its resolved value in light + dark.',
    url: 'https://ds.interlace.tools/semantics-catalog',
  },
};

interface Catalogue {
  brand: { light: Record<string, string>; dark: Record<string, string> };
  semantics: { light: Record<string, string>; dark: Record<string, string> };
}

function loadCatalogue(): Catalogue {
  // Read at build time / SSR — the JSON is regenerated by
  // `apps/registry/scripts/build-semantics-catalog.mjs` (wired into the
  // registry prebuild step). Fall back to an empty shape so the page
  // renders cleanly in dev even before the script has run.
  const path = resolve(
    process.cwd(),
    'public/data/semantics-catalogue.json',
  );
  try {
    return JSON.parse(readFileSync(path, 'utf-8'));
  } catch {
    return {
      brand: { light: {}, dark: {} },
      semantics: { light: {}, dark: {} },
    };
  }
}

export default function SemanticsCataloguePage() {
  const cat = loadCatalogue();
  return (
    <div className="bg-background text-foreground min-h-screen">
      <SiteNav />

      <main className="mx-auto max-w-6xl px-6 py-16">
        <nav aria-label="Breadcrumb" className="text-muted-foreground text-sm">
          <Link href="/" className="hover:text-foreground transition-colors">
            ← All components
          </Link>
        </nav>

        <h1 className="mt-6 text-4xl font-bold tracking-tight text-balance">
          Semantics Catalogue
        </h1>
        <p className="text-muted-foreground mt-3 max-w-2xl text-lg">
          Every Interlace semantic token, its resolved value in light +
          dark, the brand primitive it points at. Auto-generated from{' '}
          <code className="font-mono text-sm">
            packages/ui/styles/interlace-theme.css
          </code>{' '}
          at build time — when the source CSS changes, this table
          changes too.
        </p>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">
            Semantic aliases
          </h2>
          <p className="text-muted-foreground mt-2">
            These are the names you consume from React (
            <code className="font-mono text-sm">bg-background</code>,{' '}
            <code className="font-mono text-sm">text-muted-foreground</code>
            ). They resolve to the brand primitives below.
          </p>
          <TokenTable
            light={cat.semantics.light}
            dark={cat.semantics.dark}
            kind="semantic"
          />
        </section>

        <section className="mt-12">
          <h2 className="text-2xl font-semibold tracking-tight">
            Brand primitives
          </h2>
          <p className="text-muted-foreground mt-2">
            These are the concrete hex values. Override these in
            <code className="font-mono text-sm">
              @layer interlace.brand
            </code>{' '}
            (see{' '}
            <Link
              href="/theme-authoring"
              className="text-primary underline-offset-4 hover:underline"
            >
              theme authoring
            </Link>
            ) to fork the brand.
          </p>
          <TokenTable
            light={cat.brand.light}
            dark={cat.brand.dark}
            kind="brand"
          />
        </section>
      </main>
    </div>
  );
}

function TokenTable({
  light,
  dark,
  kind,
}: {
  light: Record<string, string>;
  dark: Record<string, string>;
  kind: 'semantic' | 'brand';
}) {
  const keys = Array.from(
    new Set([...Object.keys(light), ...Object.keys(dark)]),
  ).sort();

  if (keys.length === 0) {
    return (
      <p className="text-muted-foreground mt-4 text-sm">
        Catalogue is empty. Run{' '}
        <code className="font-mono">
          node apps/registry/scripts/build-semantics-catalog.mjs
        </code>{' '}
        to regenerate.
      </p>
    );
  }

  return (
    <div className="border-border mt-4 overflow-x-auto rounded-md border">
      <table className="w-full border-collapse text-sm">
        <thead className="bg-muted">
          <tr>
            <th className="p-sm text-left font-semibold">Token</th>
            <th className="p-sm text-left font-semibold">Light</th>
            <th className="p-sm text-left font-semibold">Dark</th>
          </tr>
        </thead>
        <tbody>
          {keys.map((key) => (
            <tr key={key} className="border-border border-t">
              <td className="p-sm font-mono">
                <code className="text-foreground">{key}</code>
              </td>
              <ValueCell value={light[key]} kind={kind} />
              <ValueCell value={dark[key]} kind={kind} />
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function ValueCell({
  value,
  kind,
}: {
  value: string | undefined;
  kind: 'semantic' | 'brand';
}) {
  if (!value) {
    return <td className="p-sm font-mono text-muted-foreground">—</td>;
  }
  const isHex = /^#[0-9a-fA-F]{3,8}$/.test(value);
  const isVar = value.startsWith('var(');
  return (
    <td className="p-sm font-mono">
      <span className="inline-flex items-center gap-xs">
        {isHex ? (
          <span
            aria-hidden
            className="border-border inline-block size-4 rounded border"
            style={{ backgroundColor: value }}
          />
        ) : null}
        <span
          className={
            isVar
              ? 'text-muted-foreground italic'
              : 'text-foreground'
          }
        >
          {value}
        </span>
        {kind === 'semantic' && isVar ? (
          <span className="text-muted-foreground text-xs">
            (alias)
          </span>
        ) : null}
      </span>
    </td>
  );
}
